label frenzyroute:
    mcn "I think...I'm gonna go with the House of Frenzy!"
    swa "Damn okay! Maybe you're new drag name should be Miss Wasted Potential. SMH."
    cup "It's okay, this just means we'll have to be enemies to lovers, [mcn]~"
    "Venus gives them a look and shoos them away."
    swa "See you around, [mcn]."
    nar "Cupid winks and and blows you a kiss before waving goodbye."
    nar "The two walk away with a flounce that you can't help but feel was a little personal."
    nar "Venus smiles sweetly at you and grabs both of your hands in hers."
    nar "You freeze a bit from how sudden the contact was, but something about her motherly aura compells you into calmness."
    ven "Welcome abroad! I know it's getting pretty late-- I'm so sorry for keeping you up."
    ven "Get some rest and take care, okay?"
    nar "She's soft and warm to hug. Slim-framed, but toned and soft."
    nar "She gives you her number before leaving."
    ven "Remember to call me, [mcn]!"
## black screen. maybe day counter? idk
label skate:
scene bg cd1
nar "She texted you an address, and told you to meet her there on Saturday morning. And, for some reason, she told you not to eat breakfast...?"
nar "You show up early."
nar "Like maybe forty five minutes early."
nar "You don't really trust the NYC subway system to run on time."
nar "It's a lot of distrust. The kind of distrust that makes you at *least* half an hour early to everything."
nar "You walk up the subway stairs and turn the corner, eyes glued to the Google Map displayed on your phone..."
nar "...and look up to find you're in front of..."
mcn "a Roller Rink?"
mcn "Wha-- Why are you here?!"
mcn "You thought you two were practicing voguing! And, isn't this a little too, ah... public?"
nar "Venus is, miracuslouly, already there! You're glad you don't have to stand around akwardly waiting for her."
nar "You follow her inside as she taps away at her phone."
nar "She seems to be completely ignoring you as she drops her duffel bag on the bench and starts stretching"
ven "Have you ever rollerskated before?"
mcn "Uh-"
menu:
    "Yes":
        ven "Coolio, how much experience do you have? With any sort of skating?"
        menu:
            "Tech decks in middle school":
                ven "I have no idea what you're talking about."
            "Tony Hawk wishes he was me":
                ven "I don't think that man rollerskates."
                ven "But your answer tells me everything I need to know about your experience..."
            "I tried it once because Tiktok made it look easy. I quit after a week.":
                ven "Hey, that's something! At least you know some of the jargon, that's a great start."
    "No":
        ven "Well, then I'm honored to be your teacher!"
        "She dramatically bows while strapping on her blades and helmet"
        mcn "But I don't have rollerskates-"
        ven "We're renting you some blades."
        mcn "..."
        ven "Don't worry! If you get fungus foot you can use the competition money to scrub it off later."
ven "And, I did tell you about the competition, right?"
nar "... what... competition"
ven "Ah, I can see by your silence that I may have neglected to mention it."
ven "Well, there's a competition coming up next week, and I already signed you up. No need to thank me."
nar "You can feel yourself start to sweat. A competition? Next week? You need a little more warning than that!"
ven "Hey."
nar "She stands up and squeezes your shoulder."
ven "Take a deep breath. I believe in you; I wouldn't have entered you if I didn't"
nar "And by some miracle, you're able to take that deep breath, and feel yourself calm down."
nar "But only by a small margin! You are *still* sweating over this."
ven "So, do you want to watch me first or are are you itching to take the plunge?"
menu:
    "Wait. You still need a minute!":
        mcn: "I'd rather just watch for now..."
        ven: "Nooo problemo. Just sit back, relax, and get your stretch on while I take the rink!"
        nar: "You... don't actually have a stretching routine, or even know what stretches you should be doing right now."
        nar: "As you're making up some stretches, Venus finishes lacing her skates and effotlessly slips onto the smooth shiny floor of the rink."
        nar: "You watch as she picks up speed, gliding across the floor and cutting through the air like a fish in the water."
        nar: "She really loves this, and it's obvious in the way that you see some stress that you hadn't even noticed before roll off of her shoulders as she relaxes."
        nar: "You also see her whizzing past some of the other skaters, turing to skate backwards a few times, and even sticking her tongue out at one person, who just rolls their eyes."
        nar: "Just as you're running out of stretching ideas, you look up and make eye contact with Venus, who is now back at the gate she entered from."
        ven: "All ready?"
        nar: "You give a trepadatious nod."
    "No point in putting it off!"
        mcn: "I... think that I'll take the plunge."
        ven: "That's what I love to hear!"
        nar: "She grins widely at you."
        ven: "But you need to stretch first! It's super important. Seriously. The last time I skipped stretching I dislocated my knee."
        nar: "You cringe. Yeah, stretching sounds like a good idea."
        nar: "Venus sits you down and shows you a bunch of stretches. You didn't realize there were so many kinds of stretches."
        nar: "After a good few minutes, she seems to think you're ready, and you both lace up your skates."
        ven: "Alright, do you think you're ready?"
        nar: "As she says it, she slips onto the shiny floor of the rink. Her balance is *literally* perfect, not even a wobble!"
        mcn: "Uh... as ready as I'll ever be?"
nar "Venus grins at you and extends a hand to help you onto the floor."
nar "You already feel incredibly unsteady on your feet, and you know it's only about to get worse."


    # siren
    # money
